### ISSUE TITLE
card padding or border

### ISSUE THREAD

**Issue by binyamin** [saurabhdaware/DEV-widget#14] opened 2019-11-27 15:00 UTC
Currently, it's difficult to distinguish the edges of the default or pink themes on a white background. Adding a padding would help. Alternatively, add a border using the `--header-bg` variable. If you're using a border, I would do away with the box shadow (from what I understand, according to material design it's an either-or)

**Comment by binyamin** [comment] 2019-11-27 15:03
![image](https://user-images.githubusercontent.com/39805353/69734552-29116e80-10fd-11ea-82bb-56eb213e0846.png)
How does this look?

**Comment by saurabhdaware** [comment] 2019-11-27 15:04
Hey, that's a great point! There is a little bit of padding right now and if I increase the value the content would get less space. but I think a light border would look really good.

**Comment by binyamin** [comment] 2019-11-27 15:06
Can I make a PR?

**Comment by saurabhdaware** [comment] 2019-11-27 15:07
![Bordered DEV widget](https://user-images.githubusercontent.com/30949385/69734826-aa94eb00-1155-11ea-8eef-c751d6f65b61.png)

How does this look?

**Comment by binyamin** [comment] 2019-11-27 15:09
I feel like it's too thin. If you want more space, You could make the username a link instead of using the button, and then make the profile picture smaller and the header overall shorter.

**Comment by saurabhdaware** [comment] 2019-11-27 15:17
That will leave very little space for the picture and it will be hard to figure out that clicking on the name can take you to the profile. I will actually promote having a view profile button since you can clearly tell what that button does.

Also, a lot of people are already using it so it is better to not make any major changes in the UI now since it will feel like a totally new widget if they update it.

About the border, If any user wants a border he can add a css
```css
dev-widget{
border:1px solid black;
}
```

and it will give them what they want.

**Comment by binyamin** [comment] 2019-11-27 15:19
true.

**Comment by binyamin** [comment] 2019-11-27 15:20
how about a 1.5px border? compromise 😜

**Comment by saurabhdaware** [comment] 2019-11-27 15:29
haha, I'm sorry but the problem is If I add a border and someone doesn't want it he cannot remove it (since the card is inside a shadow root which is not directly accessible) but if there is no border and someone want to add a border he can add it from the CSS. So let's just leave it to the user
 I am closing this for now but in the future, if a lot of people ask for this I will reopen this issue.

Thank you for your suggestions though I would love to see more suggestions 🦄

**Closed as completed by saurabhdaware** 2019-11-27 15:29 UTC
